[workspace]

members = [
    "ferox",
]
exclude = [
    "stm32",
]
resolver = "2"

[profile.dev]
debug = true
lto = true
opt-level = "z"
incremental = true

[profile.release]
debug = false
lto = true
opt-level = "z"
incremental = true
