[package]
name = "ferox"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-executor = { version = "0.6.3", features = ["arch-cortex-m", "executor-thread", "integrated-timers"] }
embassy-futures = "0.1.1"
embassy-stm32 = { version = "0.1.0", features = ["memory-x", "stm32h723zg", "time-driver-any", "exti", "unstable-pac"] }
embassy-sync = "0.6.1"
embassy-time = { version = "0.3.2", features = ["tick-hz-32_768"] }
panic-halt = "1.0.0"
defmt = { version = "0.3.10", optional = true }
defmt-rtt = { version = "0.4.1", optional = true }
panic-probe = { version = "0.3.2", features = ["print-defmt"], optional = true }

[features]
defmt = ["dep:defmt"]
defmt-rtt = ["dep:defmt-rtt"]
panic-probe = ["dep:panic-probe"]
default = []
debug = [
    "defmt",
    "defmt-rtt",
    "panic-probe",
    "embassy-executor/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-stm32/defmt",
]

[target.'cfg(target_arch = "arm")'.dev-dependencies]
heapless = "0.8"
