[package]
name = "ferox"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
static_cell = "2.1"
heapless = "0.8"
defmt = { version = "0.3", optional = true }

[features]
defmt = [ "dep:defmt" ]
