# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
name: Basic

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: moonrepo/setup-rust@v1.2.1
        with:
          inherit-toolchain: true

      - name: Run cargo check
        run: cargo check --all-features

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: libudev
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: moonrepo/setup-rust@v1.2.1
        with:
          inherit-toolchain: true

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings 
